USE ESTOQUE;
CREATE TABLE USUARIOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CARGO VARCHAR(50) NOT NULL,
	SENHA VARCHAR(255) NOT NULL
)

CREATE TABLE PRODUTOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	DESCRICAO TEXT,
	VALOR DECIMAL(10,2) NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	USUARIO_ID INTEGER NOT NULL,
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
)

INSERT INTO `usuarios` (`ID`, `NOME`, `EMAIL`, `CARGO`, `SENHA`) VALUES
	(1, 'TESTE', 'sgt', 'Administrador', '25f9e794323b453885f5181f1b624d0b');
/*
	Senha => 123456789
*/